# Generated by Django 5.1.5 on 2026-03-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0004_alter_petrequest_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/'),
        ),
    ]
